In [1]:
import numpy as np

In [31]:
x=np.array([1,2,3,4,5]) 
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [32]:
k = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
def mov_avg(k, n=3):
    a = np.cumsum(k)
    a[n:] = a[n:] - a[:-n]
    return a[n-1:]/n
mov_avg(k)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])